**Khai phá dữ liệu - 21TTH KDL**

Họ và tên: Lâm Gia Phú

Mã số sinh viên: 21281004

Bài tập về nhà tuần 1


# Yêu cầu 1: Cài đặt và thực thi mục 1 trên máy tính

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd
import numpy as np
from sklearn import preprocessing

# Load dữ liệu
df = pd.read_csv('/content/drive/MyDrive/HCMUS-DM/Lab01/data.csv', delimiter=',')


df = df.set_index('ID')
print(df)

   First Name Last Name  Age Gender Department  Salary Date of Joining
ID                                                                    
1        John       Doe   25      M      Sales    50.0        1/1/2020
2        Jane     Smith   30      F  Marketing    60.0        6/1/2018
3         Bod   Johnson   45      M         HR    70.0        9/1/2016
4       Alice  Williams   33      F         IT    80.0        2/1/2017
5       James     Brown   27      M      Sales    55.0        3/1/2019
6       Sarah       Lee   32      F  Marketing    65.0       12/1/2018
7     Michael     Davis   39      M         HR     NaN        8/1/2015
8       Susan    Miller   42      F         IT    90.0       11/1/2014
9       David    Wilson   28      M      Sales    60.0        5/1/2020
10      Emily     Brown   35      F  Marketing    55.0        4/1/2017
11       John       Doe   25      M      Sales    50.0        1/1/2020
12       John       Doe   25      M      Sales    50.0        1/1/2020


In [ ]:
#2. Kiểm tra các giá trị missing
print(df.isnull().sum())

#làm đầy các giá trị missing bằng giá trị trung bình
df['Salary'].fillna(df['Salary'].mean(), inplace = True)

First Name         0
Last Name          0
Age                0
Gender             0
Department         0
Salary             1
Date of Joining    0
dtype: int64


In [ ]:
# 3. Kiểm tra giá trị giống nhau
print(df.duplicated().sum())

## loại bỏ các dòng giống nhau
df = df.drop_duplicates()
print(df)


2
   First Name Last Name  Age Gender Department     Salary Date of Joining
ID                                                                       
1        John       Doe   25      M      Sales  50.000000        1/1/2020
2        Jane     Smith   30      F  Marketing  60.000000        6/1/2018
3         Bod   Johnson   45      M         HR  70.000000        9/1/2016
4       Alice  Williams   33      F         IT  80.000000        2/1/2017
5       James     Brown   27      M      Sales  55.000000        3/1/2019
6       Sarah       Lee   32      F  Marketing  65.000000       12/1/2018
7     Michael     Davis   39      M         HR  62.272727        8/1/2015
8       Susan    Miller   42      F         IT  90.000000       11/1/2014
9       David    Wilson   28      M      Sales  60.000000        5/1/2020
10      Emily     Brown   35      F  Marketing  55.000000        4/1/2017


In [ ]:
# Mã hóa dữ liệu categorical
df = pd.get_dummies(df, columns = ['Gender', 'Department'])

In [ ]:
# Xử lý dữ liệu datetime
## chuyển cột date thành một đối tượng datetime

df['Date of Joining'] = pd.to_datetime(df['Date of Joining'])
##extract month and day of week from date to column
df['month'] = df['Date of Joining'].dt.month
df['day_of_week'] = df['Date of Joining'].dt.day_name()

## drop the orginal 'Date' column
df = df.drop('Date of Joining', axis = 1)
print(df)

   First Name Last Name  Age     Salary  Gender_F  Gender_M  Department_HR  \
ID                                                                           
1        John       Doe   25  50.000000     False      True          False   
2        Jane     Smith   30  60.000000      True     False          False   
3         Bod   Johnson   45  70.000000     False      True           True   
4       Alice  Williams   33  80.000000      True     False          False   
5       James     Brown   27  55.000000     False      True          False   
6       Sarah       Lee   32  65.000000      True     False          False   
7     Michael     Davis   39  62.272727     False      True           True   
8       Susan    Miller   42  90.000000      True     False          False   
9       David    Wilson   28  60.000000     False      True          False   
10      Emily     Brown   35  55.000000      True     False          False   

    Department_IT  Department_Marketing  Department_Sales  mont

In [ ]:
# xử lý các giá trị ngoại lai
# chuẩn hóa và scale dữ liệu
df1 = df.drop(['First Name', 'Last Name', 'day_of_week'], axis = 1)
array = df1.values
print(array)

## sử dụng RobusstScaler() để loại bỏ những giá trị ngoại lai
scaler = preprocessing.RobustScaler()
robust_df = scaler.fit_transform(array)
robust_df - pd.DataFrame(robust_df)


## Chuẩn hóa dữ liệu bằng phương pháp z-score (Standard)
scaler = preprocessing.StandardScaler()
standard = scaler.fit_transform(array)
standard_df = pd.DataFrame(standard, index = df.index)
print('Chuan hoa du lieu: \n', standard_df)

## Scale dữ liệu bằng phương pháp minmax
scaler = preprocessing.MinMaxScaler()
minmax = scaler.fit_transform(array)
minmax_df = pd.DataFrame(minmax, index = df.index)
print('Scaling du lieu: \n',minmax_df)

[[25 50.0 False True False False False True 1]
 [30 60.0 True False False False True False 6]
 [45 70.0 False True True False False False 9]
 [33 80.0 True False False True False False 2]
 [27 55.0 False True False False False True 3]
 [32 65.0 True False False False True False 12]
 [39 62.27272727272727 False True True False False False 8]
 [42 90.0 True False False True False False 11]
 [28 60.0 False True False False False True 5]
 [35 55.0 True False False False True False 4]]
Chuan hoa du lieu: 
            0         1    2    3    4    5         6         7         8
ID                                                                      
1  -1.365940 -1.264391 -1.0  1.0 -0.5 -0.5 -0.654654  1.527525 -1.420508
2  -0.571789 -0.405854  1.0 -1.0 -0.5 -0.5  1.527525 -0.654654 -0.027853
3   1.810665  0.452683 -1.0  1.0  2.0 -0.5 -0.654654 -0.654654  0.807740
4  -0.095298  1.311220  1.0 -1.0 -0.5  2.0 -0.654654 -0.654654 -1.141977
5  -1.048280 -0.835122 -1.0  1.0 -0.5 -0.5 -0.654654  1

In [ ]:
# Rời rạc hóa dữ liệu
# 2.a sử dụng pd.cut()
# 10 equi-width ranges với cột đầu tiên của standard_df
df2 = standard_df.copy()
df2['equi-width_column0'] = pd.cut(x=df2[0], bins=10)
print('Roi rac hoa cot 0 bang 10 equi-width ranges: \n', df2)

Roi rac hoa cot 0 bang 10 equi-width ranges: 
            0         1    2    3    4    5         6         7         8  \
ID                                                                         
1  -1.365940 -1.264391 -1.0  1.0 -0.5 -0.5 -0.654654  1.527525 -1.420508   
2  -0.571789 -0.405854  1.0 -1.0 -0.5 -0.5  1.527525 -0.654654 -0.027853   
3   1.810665  0.452683 -1.0  1.0  2.0 -0.5 -0.654654 -0.654654  0.807740   
4  -0.095298  1.311220  1.0 -1.0 -0.5  2.0 -0.654654 -0.654654 -1.141977   
5  -1.048280 -0.835122 -1.0  1.0 -0.5 -0.5 -0.654654  1.527525 -0.863446   
6  -0.254128  0.023415  1.0 -1.0 -0.5 -0.5  1.527525 -0.654654  1.643333   
7   0.857683 -0.210732 -1.0  1.0  2.0 -0.5 -0.654654 -0.654654  0.529209   
8   1.334174  2.169757  1.0 -1.0 -0.5  2.0 -0.654654 -0.654654  1.364802   
9  -0.889449 -0.405854 -1.0  1.0 -0.5 -0.5 -0.654654  1.527525 -0.306384   
10  0.222362 -0.835122  1.0 -1.0 -0.5 -0.5  1.527525 -0.654654 -0.584915   

   equi-width_column0  
ID              

In [ ]:
# 2.b sử dụng pd.qcut()
# 10 equi-width ranges với cột đầu tiên của standard_df
df3 = standard_df.copy()
df3['equi-depth_column0'] = pd.qcut(x=df3[0], q = 10)
print('Roi rac hoa cot 0 bang 10 equi-depth ranges: \n', df3)

Roi rac hoa cot 0 bang 10 equi-depth ranges: 
            0         1    2    3    4    5         6         7         8  \
ID                                                                         
1  -1.365940 -1.264391 -1.0  1.0 -0.5 -0.5 -0.654654  1.527525 -1.420508   
2  -0.571789 -0.405854  1.0 -1.0 -0.5 -0.5  1.527525 -0.654654 -0.027853   
3   1.810665  0.452683 -1.0  1.0  2.0 -0.5 -0.654654 -0.654654  0.807740   
4  -0.095298  1.311220  1.0 -1.0 -0.5  2.0 -0.654654 -0.654654 -1.141977   
5  -1.048280 -0.835122 -1.0  1.0 -0.5 -0.5 -0.654654  1.527525 -0.863446   
6  -0.254128  0.023415  1.0 -1.0 -0.5 -0.5  1.527525 -0.654654  1.643333   
7   0.857683 -0.210732 -1.0  1.0  2.0 -0.5 -0.654654 -0.654654  0.529209   
8   1.334174  2.169757  1.0 -1.0 -0.5  2.0 -0.654654 -0.654654  1.364802   
9  -0.889449 -0.405854 -1.0  1.0 -0.5 -0.5 -0.654654  1.527525 -0.306384   
10  0.222362 -0.835122  1.0 -1.0 -0.5 -0.5  1.527525 -0.654654 -0.584915   

   equi-depth_column0  
ID              

# Yêu cầu 2: Làm tiếp những chổ chưa hoàn chỉnh ở mục 2


In [ ]:
!pip install -U scikit-learn


In [ ]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import KBinsDiscretizer

df = pd.read_csv('/content/drive/MyDrive/HCMUS-DM/Lab01/arrhythmia/arrhythmia.data', delimiter = ',', header = None)

print(df)


     0    1    2    3    4    5    6    7    8    9    ...  270   271   272  \
0     75    0  190   80   91  193  371  174  121  -16  ...  0.0   9.0  -0.9   
1     56    1  165   64   81  174  401  149   39   25  ...  0.0   8.5   0.0   
2     54    0  172   95  138  163  386  185  102   96  ...  0.0   9.5  -2.4   
3     55    0  175   94  100  202  380  179  143   28  ...  0.0  12.2  -2.2   
4     75    0  190   80   88  181  360  177  103  -16  ...  0.0  13.1  -3.6   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...   ...   
447   53    1  160   70   80  199  382  154  117  -37  ...  0.0   4.3  -5.0   
448   37    0  190   85  100  137  361  201   73   86  ...  0.0  15.6  -1.6   
449   36    0  166   68  108  176  365  194  116  -85  ...  0.0  16.3 -28.6   
450   32    1  155   55   93  106  386  218   63   54  ... -0.4  12.0  -0.7   
451   78    1  160   70   79  127  364  138   78   28  ...  0.0  10.4  -1.8   

     273  274  275  276   277   278  279  
0    0.0

In [ ]:
# Quan sát dữ liệu
## Kiểu dữ liệu
print(df.dtypes)

##
## Chọn các cột có kiểu dữ liệu là 'object' (kiểu dữ liệu chuỗi)
string_columns = df.select_dtypes(include=['object']).columns

if len(string_columns) > 0:
    print("Các cột chứa kiểu dữ liệu string:")
    print(string_columns)
else:
    print("Không có cột nào chứa kiểu dữ liệu string.")

0        int64
1        int64
2        int64
3        int64
4        int64
        ...   
275    float64
276    float64
277    float64
278    float64
279      int64
Length: 280, dtype: object
Các cột chứa kiểu dữ liệu string:
Index([10, 11, 12, 13, 14], dtype='int64')


In [ ]:
# Làm sạch dữ liệu


##1. Loại bỏ các giá trị outlier và chuyển nó thành NaN
df = df.apply(pd.to_numeric, errors='coerce')

##2. Kiểm tra các giá trị missing
print(df.isnull().sum())

##làm đầy các giá trị missing bằng giá trị trung bình
df.fillna(df.mean(), inplace = True)
## 3. Kiểm tra giá trị giống nhau
print(df.duplicated().sum())

## loại bỏ các dòng giống nhau
df = df.drop_duplicates()

print(df)


0      0
1      0
2      0
3      0
4      0
      ..
275    0
276    0
277    0
278    0
279    0
Length: 280, dtype: int64
0
     0    1    2    3    4    5    6    7    8    9    ...  270   271   272  \
0     75    0  190   80   91  193  371  174  121  -16  ...  0.0   9.0  -0.9   
1     56    1  165   64   81  174  401  149   39   25  ...  0.0   8.5   0.0   
2     54    0  172   95  138  163  386  185  102   96  ...  0.0   9.5  -2.4   
3     55    0  175   94  100  202  380  179  143   28  ...  0.0  12.2  -2.2   
4     75    0  190   80   88  181  360  177  103  -16  ...  0.0  13.1  -3.6   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...   ...   
447   53    1  160   70   80  199  382  154  117  -37  ...  0.0   4.3  -5.0   
448   37    0  190   85  100  137  361  201   73   86  ...  0.0  15.6  -1.6   
449   36    0  166   68  108  176  365  194  116  -85  ...  0.0  16.3 -28.6   
450   32    1  155   55   93  106  386  218   63   54  ... -0.4  12.0  -0.7   
451 

In [ ]:
# xử lý các giá trị ngoại lai
# chuẩn hóa và scale dữ liệu
df1 = df.copy()
array = df1.values
print(array)

## sử dụng RobusstScaler() để loại bỏ những giá trị ngoại lai
scaler = preprocessing.RobustScaler()
robust_df = scaler.fit_transform(array)
robust_df - pd.DataFrame(robust_df)


## Chuẩn hóa dữ liệu bằng phương pháp z-score (Standard)
scaler = preprocessing.StandardScaler()
standard = scaler.fit_transform(array)
standard_df = pd.DataFrame(standard, index = df.index)
print('Chuan hoa du lieu: \n', standard_df)

## Scale dữ liệu bằng phương pháp minmax
scaler = preprocessing.MinMaxScaler()
minmax = scaler.fit_transform(array)
minmax_df = pd.DataFrame(minmax, index = df.index)
print('Scaling du lieu: \n',minmax_df)

[[ 75.    0.  190.  ...  23.3  49.4   8. ]
 [ 56.    1.  165.  ...  20.4  38.8   6. ]
 [ 54.    0.  172.  ...  12.3  49.   10. ]
 ...
 [ 36.    0.  166.  ... -44.2 -33.2   2. ]
 [ 32.    1.  155.  ...  25.   46.6   1. ]
 [ 78.    1.  160.  ...  21.3  32.8   1. ]]
Chuan hoa du lieu: 
           0         1         2         3         4         5         6    \
0    1.734439 -1.107520  0.641327  0.713814  0.135505  0.844945  0.113709   
1    0.579312  0.902918 -0.031998 -0.251644 -0.516072  0.420769  1.013301   
2    0.457720 -1.107520  0.156533  1.618932  3.197915  0.175193  0.563505   
3    0.518516 -1.107520  0.237332  1.558590  0.721924  1.045871  0.383587   
4    1.734439 -1.107520  0.641327  0.713814 -0.059968  0.577044 -0.216141   
..        ...       ...       ...       ...       ...       ...       ...   
447  0.396924  0.902918 -0.166663  0.110403 -0.581229  0.978896  0.443560   
448 -0.575815 -1.107520  0.641327  1.015520  0.721924 -0.405260 -0.186154   
449 -0.636611 -1.10752

In [ ]:
# Rời rạc hóa mỗi thuộc tính số hóa thành
## 10 equi-width ranges
df2 = standard_df.copy()
df2['equi-width_column0'] = pd.cut(x=df2[0], bins=10)
print('Roi rac hoa cot 0 bang 10 equi-width ranges: \n', df2)


## 10 equi-depth ranges
df3 = standard_df.copy()
df3['equi-depth_column0'] = pd.qcut(x=df3[0], q = 10)
print('Roi rac hoa cot 0 bang 10 equi-depth ranges: \n', df3)

Roi rac hoa cot 0 bang 10 equi-width ranges: 
             0         1         2         3         4         5         6  \
0    1.734439 -1.107520  0.641327  0.713814  0.135505  0.844945  0.113709   
1    0.579312  0.902918 -0.031998 -0.251644 -0.516072  0.420769  1.013301   
2    0.457720 -1.107520  0.156533  1.618932  3.197915  0.175193  0.563505   
3    0.518516 -1.107520  0.237332  1.558590  0.721924  1.045871  0.383587   
4    1.734439 -1.107520  0.641327  0.713814 -0.059968  0.577044 -0.216141   
..        ...       ...       ...       ...       ...       ...       ...   
447  0.396924  0.902918 -0.166663  0.110403 -0.581229  0.978896  0.443560   
448 -0.575815 -1.107520  0.641327  1.015520  0.721924 -0.405260 -0.186154   
449 -0.636611 -1.107520 -0.005065 -0.010279  1.243185  0.465419 -0.066209   
450 -0.879796  0.902918 -0.301328 -0.794714  0.265820 -1.097337  0.563505   
451  1.916828  0.902918 -0.166663  0.110403 -0.646387 -0.628511 -0.096195   

            7         8     

# Yêu cầu 3: PCA
Sử dụng mục 1 để làm sạch dữ liệu và tiền xử lý dữ liệu, và sử dụng PCA trong
thư viện sklearn để làm mục 3.


In [ ]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import KBinsDiscretizer
from sklearn.decomposition import PCA

# Đọc dữ liệu
df = pd.read_csv('/content/drive/MyDrive/HCMUS-DM/Lab01/musk+version+1/clean1.data', delimiter = ',', header = None)
print(df.head())




        0        1    2    3    4    5    6    7    8    9    ...  159  160  \
0  MUSK-188  188_1+1   42 -198 -109  -75 -117   11   23  -88  ...  -74 -129   
1  MUSK-188  188_1+2   42 -191 -142  -65 -117   55   49 -170  ... -302   60   
2  MUSK-188  188_1+3   42 -191 -142  -75 -117   11   49 -161  ...  -73 -127   
3  MUSK-188  188_1+4   42 -198 -110  -65 -117   55   23  -95  ... -302   60   
4  MUSK-190  190_1+1   42 -198 -102  -75 -117   10   24  -87  ...  -73 -127   

   161  162  163  164  165  166  167  168  
0 -120  -38   30   48  -37    6   30  1.0  
1 -120  -39   31   48  -37    5   30  1.0  
2 -120  -38   30   48  -37    5   31  1.0  
3 -120  -39   30   48  -37    6   30  1.0  
4   51  128  144   43  -30   14   26  1.0  

[5 rows x 169 columns]


In [ ]:
# Làm sạch dữ liệu
##1. Kiểm tra các giá trị missing
print(df.isnull().sum())

## 2. Kiểm tra giá trị giống nhau
print(df.duplicated().sum())

## loại bỏ các dòng giống nhau
df = df.drop_duplicates()





0      0
1      0
2      0
3      0
4      0
      ..
164    0
165    0
166    0
167    0
168    0
Length: 169, dtype: int64
0


In [ ]:
df.to_csv('a.csv')

In [ ]:
# xử lý các giá trị ngoại lai
# chuẩn hóa và scale dữ liệu
## Bỏ đi 2 cột đầu là molecule_name và conformation_name
df1 = df.drop(df.columns[[0, 1]], axis = 1)
array = df1.values
print(array)

## sử dụng RobusstScaler() để loại bỏ những giá trị ngoại lai
scaler = preprocessing.RobustScaler()
robust_df = scaler.fit_transform(array)
robust_df - pd.DataFrame(robust_df)


## Chuẩn hóa dữ liệu bằng phương pháp z-score (Standard)
scaler = preprocessing.StandardScaler()
standard = scaler.fit_transform(array)
standard_df = pd.DataFrame(standard, index = df.index)
print('Chuan hoa du lieu: \n', standard_df)

## Scale dữ liệu bằng phương pháp minmax
scaler = preprocessing.MinMaxScaler()
minmax = scaler.fit_transform(array)
minmax_df = pd.DataFrame(minmax, index = df.index)
print('Scaling du lieu: \n',minmax_df)


[[  42. -198. -109. ...    6.   30.    1.]
 [  42. -191. -142. ...    5.   30.    1.]
 [  42. -191. -142. ...    5.   31.    1.]
 ...
 [  43. -102.  -20. ...  -19.  -36.    0.]
 [  39.  -58.   27. ...    3.   74.    0.]
 [  52. -121.  -24. ...   12.   96.    0.]]
Chuan hoa du lieu: 
           0         1         2         3         4         5         6    \
0    0.180913 -0.882527 -0.430628 -1.205030 -0.163966  0.225832  0.372274   
1    0.180913 -0.803181 -0.908198 -1.072468 -0.163966  0.704464  0.616523   
2    0.180913 -0.803181 -0.908198 -1.205030 -0.163966  0.225832  0.616523   
3    0.180913 -0.882527 -0.445100 -1.072468 -0.163966  0.704464  0.372274   
4    0.180913 -0.882527 -0.329325 -1.205030 -0.163966  0.214954  0.381668   
..        ...       ...       ...       ...       ...       ...       ...   
471  0.568318 -0.893863 -1.183162  0.173611  0.603259 -0.829332 -0.294713   
472 -0.040461 -0.032386 -0.864782  0.186867 -0.163966 -0.851088  2.166562   
473  0.236257  0.20565

In [ ]:
def PCA(data, n_component):
    # Ma trận hiệp phương sai
    covariance_matrix = np.cov(data.T)

    # Giá trị kỳ dị và vector của nó
    eigenvalues, eigenvectors = np.linalg.eig(covariance_matrix)

    # Sắp xếp giá trị
    sorted_indices = np.argsort(eigenvalues)[::-1]
    eigenvalues = eigenvalues[sorted_indices]
    eigenvectors = eigenvectors[:, sorted_indices]

    # Chọn số thành chính muốn giữ lại
    k = n_component
    principal_components = eigenvectors[:, :k]

    transformed_data = np.dot(data, principal_components)
    print("eigenvalues: ", eigenvalues)
    print("eigenvector: ", eigenvectors)

    return transformed_data

# Kích  thước của data
print(standard_df.shape)

# In ra kết quả sau khi PCA khi chọn n_component là 200 và data dùng là standard_df
print('Data sau khi PCA: ',PCA(standard_df, 200))



(476, 167)
eigenvalues:  [5.18912407e+01 2.31614115e+01 1.26896951e+01 8.70167407e+00
 8.18405986e+00 6.81216986e+00 5.45722632e+00 5.13118179e+00
 3.31330057e+00 2.93624343e+00 2.57815316e+00 2.38456538e+00
 2.21836924e+00 2.12858360e+00 1.81707022e+00 1.67647421e+00
 1.44502649e+00 1.37958938e+00 1.25950055e+00 1.18773302e+00
 1.12413571e+00 1.06105232e+00 1.05265358e+00 9.71230587e-01
 9.30723995e-01 8.86183849e-01 8.60660641e-01 8.16617121e-01
 8.01913380e-01 7.48508590e-01 6.70353094e-01 6.64226035e-01
 6.40028005e-01 5.54818628e-01 5.02487253e-01 4.87770595e-01
 4.71648859e-01 4.30446086e-01 4.10162776e-01 3.94971975e-01
 3.38261309e-01 3.31739932e-01 3.10343257e-01 2.87700390e-01
 2.74507131e-01 2.69940884e-01 2.47250935e-01 2.39282725e-01
 2.16301584e-01 2.05604380e-01 1.97294367e-01 1.88355770e-01
 1.79152281e-01 1.72879404e-01 1.59503951e-01 1.49205339e-01
 1.44283392e-01 1.37736601e-01 1.27966888e-01 1.25115144e-01
 1.18168079e-01 1.04647575e-01 1.00968491e-01 9.11529759e-02